spring:
  application:
    name: rl-rest-mvc
  jackson:
    default-property-inclusion: always
  main:
    allow-bean-definition-overriding: true

beer:
  api:
    path: /api/v1/beer
customer:
  api:
    path: /api/v1/customer

